from dagster import StaticPartitionsDefinition
from google.cloud.bigquery import SchemaField

PART_D_DATASETS = {
    2023: "6428fad7-4fb1-454c-93a4-772934d73922",
    2022: "bed99012-c527-4d9d-92ea-67ec2510abea",
    2021: "3f7ab9ce-6fb6-4e6b-9af3-b681f2d3a95e",
    2020: "ed6548c1-c905-4fdf-84cc-1c897ca6210d",
    2019: "007f61da-2c20-4c80-90a5-88be67c8d022",
    2018: "a422bf49-e5b3-429a-862f-723db5e15704",
    2017: "dc524dbb-6115-48c9-a4dc-aa4fb0d21b69",
    2016: "9c3eb417-a310-42d2-8065-9e2129e6a680",
    2015: "2aa87eb6-6555-42fa-a51d-4a332ab7d5e8",
    2014: "8c3806d2-0692-4564-ab38-7bc19206521c",
    2013: "93645ea4-1a3f-4444-95c5-c109e6a4b267",
}

year_partitions = StaticPartitionsDefinition(
    [str(y) for y in sorted(PART_D_DATASETS.keys())]
)

PART_D_STAGING_SCHEMA = [
    SchemaField("PRSCRBR_NPI", "FLOAT64", mode="NULLABLE"),
    SchemaField("Prscrbr_Last_Org_Name", "STRING", mode="NULLABLE"),
    SchemaField("Prscrbr_First_Name", "STRING", mode="NULLABLE"),
    SchemaField("Prscrbr_MI", "STRING", mode="NULLABLE"),
    SchemaField("Prscrbr_Crdntls", "STRING", mode="NULLABLE"),
    SchemaField("Prscrbr_Ent_Cd", "STRING", mode="NULLABLE"),
    SchemaField("Prscrbr_St1", "STRING", mode="NULLABLE"),
    SchemaField("Prscrbr_St2", "STRING", mode="NULLABLE"),
    SchemaField("Prscrbr_City", "STRING", mode="NULLABLE"),
    SchemaField("Prscrbr_State_Abrvtn", "STRING", mode="NULLABLE"),
    SchemaField("Prscrbr_State_FIPS", "STRING", mode="NULLABLE"),
    SchemaField("Prscrbr_zip5", "FLOAT64", mode="NULLABLE"),
    SchemaField("Prscrbr_RUCA", "STRING", mode="NULLABLE"),
    SchemaField("Prscrbr_RUCA_Desc", "STRING", mode="NULLABLE"),
    SchemaField("Prscrbr_Cntry", "STRING", mode="NULLABLE"),
    SchemaField("Prscrbr_Type", "STRING", mode="NULLABLE"),
    SchemaField("Prscrbr_Type_src", "STRING", mode="NULLABLE"),
    SchemaField("Tot_Clms", "FLOAT64", mode="NULLABLE"),
    SchemaField("Tot_30day_Fills", "FLOAT64", mode="NULLABLE"),
    SchemaField("Tot_Drug_Cst", "FLOAT64", mode="NULLABLE"),
    SchemaField("Tot_Day_Suply", "FLOAT64", mode="NULLABLE"),
    SchemaField("Tot_Benes", "FLOAT64", mode="NULLABLE"),
    SchemaField("GE65_Sprsn_Flag", "STRING", mode="NULLABLE"),
    SchemaField("GE65_Tot_Clms", "FLOAT64", mode="NULLABLE"),
    SchemaField("GE65_Tot_30day_Fills", "FLOAT64", mode="NULLABLE"),
    SchemaField("GE65_Tot_Drug_Cst", "FLOAT64", mode="NULLABLE"),
    SchemaField("GE65_Tot_Day_Suply", "FLOAT64", mode="NULLABLE"),
    SchemaField("GE65_Bene_Sprsn_Flag", "STRING", mode="NULLABLE"),
    SchemaField("GE65_Tot_Benes", "FLOAT64", mode="NULLABLE"),
    SchemaField("Brnd_Sprsn_Flag", "STRING", mode="NULLABLE"),
    SchemaField("Brnd_Tot_Clms", "FLOAT64", mode="NULLABLE"),
    SchemaField("Brnd_Tot_Drug_Cst", "FLOAT64", mode="NULLABLE"),
    SchemaField("Gnrc_Sprsn_Flag", "STRING", mode="NULLABLE"),
    SchemaField("Gnrc_Tot_Clms", "FLOAT64", mode="NULLABLE"),
    SchemaField("Gnrc_Tot_Drug_Cst", "FLOAT64", mode="NULLABLE"),
    SchemaField("Othr_Sprsn_Flag", "STRING", mode="NULLABLE"),
    SchemaField("Othr_Tot_Clms", "FLOAT64", mode="NULLABLE"),
    SchemaField("Othr_Tot_Drug_Cst", "FLOAT64", mode="NULLABLE"),
    SchemaField("MAPD_Sprsn_Flag", "STRING", mode="NULLABLE"),
    SchemaField("MAPD_Tot_Clms", "FLOAT64", mode="NULLABLE"),
    SchemaField("MAPD_Tot_Drug_Cst", "FLOAT64", mode="NULLABLE"),
    SchemaField("PDP_Sprsn_Flag", "STRING", mode="NULLABLE"),
    SchemaField("PDP_Tot_Clms", "FLOAT64", mode="NULLABLE"),
    SchemaField("PDP_Tot_Drug_Cst", "FLOAT64", mode="NULLABLE"),
    SchemaField("LIS_Sprsn_Flag", "STRING", mode="NULLABLE"),
    SchemaField("LIS_Tot_Clms", "FLOAT64", mode="NULLABLE"),
    SchemaField("LIS_Drug_Cst", "FLOAT64", mode="NULLABLE"),
    SchemaField("NonLIS_Sprsn_Flag", "STRING", mode="NULLABLE"),
    SchemaField("NonLIS_Tot_Clms", "FLOAT64", mode="NULLABLE"),
    SchemaField("NonLIS_Drug_Cst", "FLOAT64", mode="NULLABLE"),
    SchemaField("Opioid_Tot_Clms", "FLOAT64", mode="NULLABLE"),
    SchemaField("Opioid_Tot_Drug_Cst", "FLOAT64", mode="NULLABLE"),
    SchemaField("Opioid_Tot_Suply", "FLOAT64", mode="NULLABLE"),
    SchemaField("Opioid_Tot_Benes", "FLOAT64", mode="NULLABLE"),
    SchemaField("Opioid_Prscrbr_Rate", "FLOAT64", mode="NULLABLE"),
    SchemaField("Opioid_LA_Tot_Clms", "FLOAT64", mode="NULLABLE"),
    SchemaField("Opioid_LA_Tot_Drug_Cst", "FLOAT64", mode="NULLABLE"),
    SchemaField("Opioid_LA_Tot_Suply", "FLOAT64", mode="NULLABLE"),
    SchemaField("Opioid_LA_Tot_Benes", "FLOAT64", mode="NULLABLE"),
    SchemaField("Opioid_LA_Prscrbr_Rate", "FLOAT64", mode="NULLABLE"),
    SchemaField("Antbtc_Tot_Clms", "FLOAT64", mode="NULLABLE"),
    SchemaField("Antbtc_Tot_Drug_Cst", "FLOAT64", mode="NULLABLE"),
    SchemaField("Antbtc_Tot_Benes", "FLOAT64", mode="NULLABLE"),
    SchemaField("Antpsyct_GE65_Sprsn_Flag", "STRING", mode="NULLABLE"),
    SchemaField("Antpsyct_GE65_Tot_Clms", "FLOAT64", mode="NULLABLE"),
    SchemaField("Antpsyct_GE65_Tot_Drug_Cst", "FLOAT64", mode="NULLABLE"),
    SchemaField("Antpsyct_GE65_Bene_Suprsn_Flag", "STRING", mode="NULLABLE"),
    SchemaField("Antpsyct_GE65_Tot_Benes", "FLOAT64", mode="NULLABLE"),
    SchemaField("Bene_Avg_Age", "FLOAT64", mode="NULLABLE"),
    SchemaField("Bene_Age_LT_65_Cnt", "FLOAT64", mode="NULLABLE"),
    SchemaField("Bene_Age_65_74_Cnt", "FLOAT64", mode="NULLABLE"),
    SchemaField("Bene_Age_75_84_Cnt", "FLOAT64", mode="NULLABLE"),
    SchemaField("Bene_Age_GT_84_Cnt", "FLOAT64", mode="NULLABLE"),
    SchemaField("Bene_Feml_Cnt", "FLOAT64", mode="NULLABLE"),
    SchemaField("Bene_Male_Cnt", "FLOAT64", mode="NULLABLE"),
    SchemaField("Bene_Race_Wht_Cnt", "FLOAT64", mode="NULLABLE"),
    SchemaField("Bene_Race_Black_Cnt", "FLOAT64", mode="NULLABLE"),
    SchemaField("Bene_Race_Api_Cnt", "FLOAT64", mode="NULLABLE"),
    SchemaField("Bene_Race_Hspnc_Cnt", "FLOAT64", mode="NULLABLE"),
    SchemaField("Bene_Race_Natind_Cnt", "FLOAT64", mode="NULLABLE"),
    SchemaField("Bene_Race_Othr_Cnt", "FLOAT64", mode="NULLABLE"),
    SchemaField("Bene_Dual_Cnt", "FLOAT64", mode="NULLABLE"),
    SchemaField("Bene_Ndual_Cnt", "FLOAT64", mode="NULLABLE"),
    SchemaField("Bene_Avg_Risk_Scre", "FLOAT64", mode="NULLABLE"),
]
