[project]
name = "claims-intelligence"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dagster>=1.13.5",
    "dagster-dbt>=0.29.5",
    "dagster-gcp>=0.29.5",
    "dagster-webserver>=1.13.5",
    "dbt-bigquery>=1.11.1",
    "pandas>=2.3.3",
    "polars>=1.40.1",
    "pyarrow>=24.0.0",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
]

[dependency-groups]
dev = [
    "dagster-dg-cli>=1.13.5",
    "ruff>=0.15.14",
]

[tool.ruff]
line-length = 88
target-version = "py313"

[tool.ruff.lint]
select = ["E", "F", "I"]  # pycodestyle, pyflakes, isort

[tool.ruff.format]
# Black-compatible formatting
quote-style = "double"

[tool.dg]
directory_type = "project"

[tool.dg.project]
root_module = "claims_intelligence"
code_location_target_module = "claims_intelligence.definitions"

[project.entry-points]
"dagster_dg_cli.registry_modules" = { claims_intelligence = "claims_intelligence.components"}

[tool.setuptools.packages.find]
include = ["claims_intelligence*"]
